<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2023-2026 Maveniverse Org.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v2.0
    which accompanies this distribution, and is available at
    https://www.eclipse.org/legal/epl-v20.html

-->
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.maveniverse.maven.toolrunner.it</groupId>
    <artifactId>jdk-hello-world</artifactId>
    <version>1.0.0</version>

    <build>
        <plugins>
            <plugin>
                <groupId>eu.maveniverse.maven.plugins</groupId>
                <artifactId>toolrunner</artifactId>
                <version>@project.version@</version>
                <executions>
                    <execution>
                        <id>tool-compile</id>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <toolName>jdk</toolName>
                            <command>javac</command>
                            <arguments>
                                <argument>hello.java</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>tool-run</id>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <toolName>jdk</toolName>
                            <command>java</command>
                            <arguments>
                                <argument>-cp</argument>
                                <argument>.</argument>
                                <argument>--option1=foo</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>eu.maveniverse.maven.toolrunner.tools</groupId>
                        <artifactId>jdk</artifactId>
                        <version>@project.version@</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>