/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.jupiter.api.Test;

public class MainTest {

    @Test
    void test() {
        Main.main(null);
    }
}