<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.maveniverse.maven.toolrunner.it</groupId>
    <artifactId>simplest-app</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <project.build.outputTimestamp>2026-04-08T12:22:26Z</project.build.outputTimestamp>
        <maven.compiler.release>17</maven.compiler.release>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.17</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.17</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <!-- Must up compiler in IT due 3.8.x -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
            </plugin>
            <plugin>
                <groupId>eu.maveniverse.maven.plugins</groupId>
                <artifactId>toolbox</artifactId>
                <version>0.15.8</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <phase>prepare-package</phase>
                        <configuration>
                            <sinkSpec>flat(${project.build.directory}/lib)</sinkSpec>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <outputDirectory>${project.build.directory}/lib</outputDirectory>
                </configuration>
            </plugin>
            <plugin>
                <groupId>eu.maveniverse.maven.plugins</groupId>
                <artifactId>toolrunner</artifactId>
                <version>@project.version@</version>
                <executions>
                    <execution>
                        <id>jpackage</id>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <toolName>jdk</toolName>
                            <command>jpackage</command>
                            <arguments>
                                <argument>--input ${project.build.directory}/lib</argument>
                                <argument>--name ${project.artifactId}</argument>
                                <argument>--main-jar ${project.artifactId}-${project.version}.jar</argument>
                                <argument>--main-class org.maveniverse.maven.toolrunner.it.simplest.Example</argument>
                                <argument>--type ${packageType}</argument>
                                <argument>--dest ${project.build.directory}/app</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>eu.maveniverse.maven.toolrunner.tools</groupId>
                        <artifactId>jdk</artifactId>
                        <version>@project.version@</version>
                    </dependency>
                </dependencies>

            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>linux</id>
            <activation>
                <os>
                    <family>linux</family>
                </os>
            </activation>
            <properties>
                <packageType>app-image</packageType>
            </properties>
        </profile>
        <profile>
            <id>windows</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <properties>
                <packageType>msi</packageType>
            </properties>
        </profile>
        <profile>
            <id>macos</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <properties>
                <packageType>dmg</packageType>
            </properties>
        </profile>
    </profiles>
</project>